name: Build
description: issues related to builds
title: "[BUILD]: "
labels: ["build"]
assignees: "sophies927"
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of the bug/issue you are experiencing.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Before submitting your request, please review past submissions to ensure that it is not a duplicate of a known issue.
        If your request has been submitted previously, please add a comment to the initial request noting that you are experiencing the same bug/issue. Most importantly, do not proceed with your submission; duplicate requests make the jobs of engineering team members more difficult, and if your request is identified as a duplicate, it will be closed.
  - type: input
    id: theme-id
    attributes:
      label: Theme identification
      description: If there is a previous issue that is similar to (but not exactly the same as) your issue, please list the issue number below.
      placeholder: ex. #12345
    validations:
      required: true
  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: Is your issue urgent?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Urgent issues fall within one of the following categories:
          - Your request is related to a perceived regression in ONNX Runtime functionality (i.e., some aspect of ONNX Runtime worked previously but is no longer functional)
          - Important use cases are blocked by the bug/issue you are encountering
          - You have a strict project-related deadline that you are going to miss if your request is not addressed in a timely manner
        If you identify that your issue is urgent, please provide more information (e.g., the regression you are experiencing, project-related deadlines you must follow, etc.).
  - type: markdown
    attributes:
      value: |
        For each of the following line items, provide the information listed to ensure that your request is addressed in a timely manner. If your submission is missing required information, a “triage:more-info-needed” label will be applied, and you will not receive a response from the engineering team until you have made necessary updates.
  - type: input
    id: os-plat-dist
    attributes:
      label: OS Platform and Distribution
      placeholder: ex. Linux Ubuntu 16.04
  - type: dropdown
    id: ort-installation
    attributes:
      label: ONNX Runtime Installation
      options:
        - Source
        - Binary
    validations:
      required: true
  - type: input
    id: ort-version
    attributes:
      label: ONNX Runtime Version
      placeholder: ex. 1.12.1
  - type: dropdown
    id: api
    attributes:
      label: API
      options:
        - C/C++
        - C#
        - Java
        - JavaScript
        - Python
        - Rust
    validations:
      required: true
  - type: input
    id: api-version
    attributes:
      label: API Version
      placeholder: ex. 3.9.13
  - type: dropdown
    id: ep
    attributes:
      label: Execution Provider
      options:
        - Arm Compute Library (ACL)
        - ArmNN
        - CoreML
        - CUDA
        - DirectML
        - DNNL
        - MIGraphX
        - Neural Networks API (NNAPI)
        - OpenVINO
        - Rockchip NPU
        - TensorRT
        - TVM
        - Vitis-AI
    validations:
      required: true
  - type: input
    id: ep-version
    attributes:
      label: EP Version
      placeholder: ex. 2022.1
  - type: input
    id: vs-version
    attributes:
      label: Visual Studio Version
  - type: input
    id: comp-version
    attributes:
      label: GCC/Compiler Version
  - type: input
    id: mod-mem
    attributes:
      label: GPU Model and Memory
  - type: markdown
    attributes:
      value: |
        Please provide enough information/code for someone else to reproduce the behavior. If an engineering team member cannot reproduce your request when reviewing it, a “triage:more-info-needed” label will be applied, and you will not receive a response from the engineering team until you have made necessary updates to your request.
        Tools like Google Colab and GitHub Codespaces can be used to more easily share and collaborate on code. If you decide to use one of these tools, please add a link to your workspace.
        Attach the ONNX model to your request (where applicable) to expedite investigation.
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
