blank_issues_enabled: false
contact_links:
  - name: ONNX Runtime GitHub Discussions
    url: https://github.com/microsoft/onnxruntime/issues
    about: For questions, discussions, and feature proposals that you would like to be reviewed by a member of the ORT engineering team, use GitHub Discussions.
  - name: ONNX Runtime GitHub Issues
    url: https://github.com/microsoft/onnxruntime/discussions
    about: Please report security vulnerabilities here.
  - name: For bugs and issues that you would like to be reviewed by a member of the ORT engineering team, use GitHub Issues.
    url: https://stackoverflow.com/questions/tagged/onnxruntime
    about: For questions, discussions, and more that do not require ORT engineering team oversight, use Stack Overflow.
